// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: audio.proto

package serviciosAudio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_ObtenerTiposAudio_FullMethodName    = "/servicios.MetadataService/ObtenerTiposAudio"
	MetadataService_ObtenerAudiosPorTipo_FullMethodName = "/servicios.MetadataService/ObtenerAudiosPorTipo"
	MetadataService_ObtenerDetalleAudio_FullMethodName  = "/servicios.MetadataService/ObtenerDetalleAudio"
	MetadataService_RegistrarUsuario_FullMethodName     = "/servicios.MetadataService/RegistrarUsuario"
	MetadataService_Login_FullMethodName                = "/servicios.MetadataService/Login"
	MetadataService_AlmacenarAudio_FullMethodName       = "/servicios.MetadataService/AlmacenarAudio"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	ObtenerTiposAudio(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TiposAudioResponse, error)
	ObtenerAudiosPorTipo(ctx context.Context, in *AudiosPorTipoRequest, opts ...grpc.CallOption) (*AudiosPorTipoResponse, error)
	ObtenerDetalleAudio(ctx context.Context, in *DetalleAudioRequest, opts ...grpc.CallOption) (*DetalleAudioResponse, error)
	RegistrarUsuario(ctx context.Context, in *RegistrarUsuarioRequest, opts ...grpc.CallOption) (*RegistrarUsuarioResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	AlmacenarAudio(ctx context.Context, in *AlmacenarAudioRequest, opts ...grpc.CallOption) (*AlmacenarAudioResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) ObtenerTiposAudio(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TiposAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TiposAudioResponse)
	err := c.cc.Invoke(ctx, MetadataService_ObtenerTiposAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ObtenerAudiosPorTipo(ctx context.Context, in *AudiosPorTipoRequest, opts ...grpc.CallOption) (*AudiosPorTipoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudiosPorTipoResponse)
	err := c.cc.Invoke(ctx, MetadataService_ObtenerAudiosPorTipo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ObtenerDetalleAudio(ctx context.Context, in *DetalleAudioRequest, opts ...grpc.CallOption) (*DetalleAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetalleAudioResponse)
	err := c.cc.Invoke(ctx, MetadataService_ObtenerDetalleAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RegistrarUsuario(ctx context.Context, in *RegistrarUsuarioRequest, opts ...grpc.CallOption) (*RegistrarUsuarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrarUsuarioResponse)
	err := c.cc.Invoke(ctx, MetadataService_RegistrarUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, MetadataService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) AlmacenarAudio(ctx context.Context, in *AlmacenarAudioRequest, opts ...grpc.CallOption) (*AlmacenarAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlmacenarAudioResponse)
	err := c.cc.Invoke(ctx, MetadataService_AlmacenarAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
type MetadataServiceServer interface {
	ObtenerTiposAudio(context.Context, *Empty) (*TiposAudioResponse, error)
	ObtenerAudiosPorTipo(context.Context, *AudiosPorTipoRequest) (*AudiosPorTipoResponse, error)
	ObtenerDetalleAudio(context.Context, *DetalleAudioRequest) (*DetalleAudioResponse, error)
	RegistrarUsuario(context.Context, *RegistrarUsuarioRequest) (*RegistrarUsuarioResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	AlmacenarAudio(context.Context, *AlmacenarAudioRequest) (*AlmacenarAudioResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) ObtenerTiposAudio(context.Context, *Empty) (*TiposAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerTiposAudio not implemented")
}
func (UnimplementedMetadataServiceServer) ObtenerAudiosPorTipo(context.Context, *AudiosPorTipoRequest) (*AudiosPorTipoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerAudiosPorTipo not implemented")
}
func (UnimplementedMetadataServiceServer) ObtenerDetalleAudio(context.Context, *DetalleAudioRequest) (*DetalleAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerDetalleAudio not implemented")
}
func (UnimplementedMetadataServiceServer) RegistrarUsuario(context.Context, *RegistrarUsuarioRequest) (*RegistrarUsuarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegistrarUsuario not implemented")
}
func (UnimplementedMetadataServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedMetadataServiceServer) AlmacenarAudio(context.Context, *AlmacenarAudioRequest) (*AlmacenarAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AlmacenarAudio not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_ObtenerTiposAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ObtenerTiposAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ObtenerTiposAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ObtenerTiposAudio(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ObtenerAudiosPorTipo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudiosPorTipoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ObtenerAudiosPorTipo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ObtenerAudiosPorTipo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ObtenerAudiosPorTipo(ctx, req.(*AudiosPorTipoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ObtenerDetalleAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetalleAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ObtenerDetalleAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ObtenerDetalleAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ObtenerDetalleAudio(ctx, req.(*DetalleAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RegistrarUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrarUsuarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RegistrarUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_RegistrarUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RegistrarUsuario(ctx, req.(*RegistrarUsuarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_AlmacenarAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlmacenarAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).AlmacenarAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_AlmacenarAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).AlmacenarAudio(ctx, req.(*AlmacenarAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerTiposAudio",
			Handler:    _MetadataService_ObtenerTiposAudio_Handler,
		},
		{
			MethodName: "ObtenerAudiosPorTipo",
			Handler:    _MetadataService_ObtenerAudiosPorTipo_Handler,
		},
		{
			MethodName: "ObtenerDetalleAudio",
			Handler:    _MetadataService_ObtenerDetalleAudio_Handler,
		},
		{
			MethodName: "RegistrarUsuario",
			Handler:    _MetadataService_RegistrarUsuario_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _MetadataService_Login_Handler,
		},
		{
			MethodName: "AlmacenarAudio",
			Handler:    _MetadataService_AlmacenarAudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audio.proto",
}

const (
	StreamingService_ReproducirAudio_FullMethodName = "/servicios.StreamingService/ReproducirAudio"
)

// StreamingServiceClient is the client API for StreamingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamingServiceClient interface {
	ReproducirAudio(ctx context.Context, in *ReproducirAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
}

type streamingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingServiceClient(cc grpc.ClientConnInterface) StreamingServiceClient {
	return &streamingServiceClient{cc}
}

func (c *streamingServiceClient) ReproducirAudio(ctx context.Context, in *ReproducirAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingService_ServiceDesc.Streams[0], StreamingService_ReproducirAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReproducirAudioRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_ReproducirAudioClient = grpc.ServerStreamingClient[AudioChunk]

// StreamingServiceServer is the server API for StreamingService service.
// All implementations must embed UnimplementedStreamingServiceServer
// for forward compatibility.
type StreamingServiceServer interface {
	ReproducirAudio(*ReproducirAudioRequest, grpc.ServerStreamingServer[AudioChunk]) error
	mustEmbedUnimplementedStreamingServiceServer()
}

// UnimplementedStreamingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingServiceServer struct{}

func (UnimplementedStreamingServiceServer) ReproducirAudio(*ReproducirAudioRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method ReproducirAudio not implemented")
}
func (UnimplementedStreamingServiceServer) mustEmbedUnimplementedStreamingServiceServer() {}
func (UnimplementedStreamingServiceServer) testEmbeddedByValue()                          {}

// UnsafeStreamingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingServiceServer will
// result in compilation errors.
type UnsafeStreamingServiceServer interface {
	mustEmbedUnimplementedStreamingServiceServer()
}

func RegisterStreamingServiceServer(s grpc.ServiceRegistrar, srv StreamingServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingService_ServiceDesc, srv)
}

func _StreamingService_ReproducirAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReproducirAudioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingServiceServer).ReproducirAudio(m, &grpc.GenericServerStream[ReproducirAudioRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingService_ReproducirAudioServer = grpc.ServerStreamingServer[AudioChunk]

// StreamingService_ServiceDesc is the grpc.ServiceDesc for StreamingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.StreamingService",
	HandlerType: (*StreamingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReproducirAudio",
			Handler:       _StreamingService_ReproducirAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "audio.proto",
}
