// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: audio.proto

package serviciosAudio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_audio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{1}
}

type TipoAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TipoAudio) Reset() {
	*x = TipoAudio{}
	mi := &file_audio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TipoAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipoAudio) ProtoMessage() {}

func (x *TipoAudio) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipoAudio.ProtoReflect.Descriptor instead.
func (*TipoAudio) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{2}
}

func (x *TipoAudio) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TipoAudio) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type AudioResumen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioResumen) Reset() {
	*x = AudioResumen{}
	mi := &file_audio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioResumen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioResumen) ProtoMessage() {}

func (x *AudioResumen) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioResumen.ProtoReflect.Descriptor instead.
func (*AudioResumen) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{3}
}

func (x *AudioResumen) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AudioResumen) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

type CampoMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clave         string                 `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	Valor         string                 `protobuf:"bytes,2,opt,name=valor,proto3" json:"valor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampoMetadata) Reset() {
	*x = CampoMetadata{}
	mi := &file_audio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampoMetadata) ProtoMessage() {}

func (x *CampoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampoMetadata.ProtoReflect.Descriptor instead.
func (*CampoMetadata) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{4}
}

func (x *CampoMetadata) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *CampoMetadata) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

type TiposAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipos         []*TipoAudio           `protobuf:"bytes,1,rep,name=tipos,proto3" json:"tipos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TiposAudioResponse) Reset() {
	*x = TiposAudioResponse{}
	mi := &file_audio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TiposAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiposAudioResponse) ProtoMessage() {}

func (x *TiposAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiposAudioResponse.ProtoReflect.Descriptor instead.
func (*TiposAudioResponse) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{5}
}

func (x *TiposAudioResponse) GetTipos() []*TipoAudio {
	if x != nil {
		return x.Tipos
	}
	return nil
}

type AudiosPorTipoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTipo        int32                  `protobuf:"varint,1,opt,name=idTipo,proto3" json:"idTipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudiosPorTipoRequest) Reset() {
	*x = AudiosPorTipoRequest{}
	mi := &file_audio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudiosPorTipoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudiosPorTipoRequest) ProtoMessage() {}

func (x *AudiosPorTipoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudiosPorTipoRequest.ProtoReflect.Descriptor instead.
func (*AudiosPorTipoRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{6}
}

func (x *AudiosPorTipoRequest) GetIdTipo() int32 {
	if x != nil {
		return x.IdTipo
	}
	return 0
}

type AudiosPorTipoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audios        []*AudioResumen        `protobuf:"bytes,1,rep,name=audios,proto3" json:"audios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudiosPorTipoResponse) Reset() {
	*x = AudiosPorTipoResponse{}
	mi := &file_audio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudiosPorTipoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudiosPorTipoResponse) ProtoMessage() {}

func (x *AudiosPorTipoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudiosPorTipoResponse.ProtoReflect.Descriptor instead.
func (*AudiosPorTipoResponse) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{7}
}

func (x *AudiosPorTipoResponse) GetAudios() []*AudioResumen {
	if x != nil {
		return x.Audios
	}
	return nil
}

type DetalleAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAudio       int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetalleAudioRequest) Reset() {
	*x = DetalleAudioRequest{}
	mi := &file_audio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetalleAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetalleAudioRequest) ProtoMessage() {}

func (x *DetalleAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetalleAudioRequest.ProtoReflect.Descriptor instead.
func (*DetalleAudioRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{8}
}

func (x *DetalleAudioRequest) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

type ReproducirAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAudio       int32                  `protobuf:"varint,1,opt,name=idAudio,proto3" json:"idAudio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReproducirAudioRequest) Reset() {
	*x = ReproducirAudioRequest{}
	mi := &file_audio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReproducirAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReproducirAudioRequest) ProtoMessage() {}

func (x *ReproducirAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReproducirAudioRequest.ProtoReflect.Descriptor instead.
func (*ReproducirAudioRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{9}
}

func (x *ReproducirAudioRequest) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

type DetalleAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdTipo        int32                  `protobuf:"varint,2,opt,name=idTipo,proto3" json:"idTipo,omitempty"`
	Titulo        string                 `protobuf:"bytes,3,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Metadatos     []*CampoMetadata       `protobuf:"bytes,4,rep,name=metadatos,proto3" json:"metadatos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetalleAudioResponse) Reset() {
	*x = DetalleAudioResponse{}
	mi := &file_audio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetalleAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetalleAudioResponse) ProtoMessage() {}

func (x *DetalleAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetalleAudioResponse.ProtoReflect.Descriptor instead.
func (*DetalleAudioResponse) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{10}
}

func (x *DetalleAudioResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DetalleAudioResponse) GetIdTipo() int32 {
	if x != nil {
		return x.IdTipo
	}
	return 0
}

func (x *DetalleAudioResponse) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *DetalleAudioResponse) GetMetadatos() []*CampoMetadata {
	if x != nil {
		return x.Metadatos
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_audio_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{11}
}

func (x *LoginRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exitoso       bool                   `protobuf:"varint,1,opt,name=exitoso,proto3" json:"exitoso,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_audio_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{12}
}

func (x *LoginResponse) GetExitoso() bool {
	if x != nil {
		return x.Exitoso
	}
	return false
}

func (x *LoginResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type RegistrarUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrarUsuarioRequest) Reset() {
	*x = RegistrarUsuarioRequest{}
	mi := &file_audio_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrarUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarUsuarioRequest) ProtoMessage() {}

func (x *RegistrarUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarUsuarioRequest.ProtoReflect.Descriptor instead.
func (*RegistrarUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{13}
}

func (x *RegistrarUsuarioRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegistrarUsuarioRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegistrarUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrado    bool                   `protobuf:"varint,1,opt,name=registrado,proto3" json:"registrado,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrarUsuarioResponse) Reset() {
	*x = RegistrarUsuarioResponse{}
	mi := &file_audio_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrarUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarUsuarioResponse) ProtoMessage() {}

func (x *RegistrarUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarUsuarioResponse.ProtoReflect.Descriptor instead.
func (*RegistrarUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{14}
}

func (x *RegistrarUsuarioResponse) GetRegistrado() bool {
	if x != nil {
		return x.Registrado
	}
	return false
}

func (x *RegistrarUsuarioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type AlmacenarAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	Artista       string                 `protobuf:"bytes,2,opt,name=artista,proto3" json:"artista,omitempty"`
	Genero        string                 `protobuf:"bytes,3,opt,name=genero,proto3" json:"genero,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Anio          string                 `protobuf:"bytes,5,opt,name=anio,proto3" json:"anio,omitempty"`
	IdTipo        int32                  `protobuf:"varint,6,opt,name=idTipo,proto3" json:"idTipo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlmacenarAudioRequest) Reset() {
	*x = AlmacenarAudioRequest{}
	mi := &file_audio_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlmacenarAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlmacenarAudioRequest) ProtoMessage() {}

func (x *AlmacenarAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlmacenarAudioRequest.ProtoReflect.Descriptor instead.
func (*AlmacenarAudioRequest) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{15}
}

func (x *AlmacenarAudioRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *AlmacenarAudioRequest) GetArtista() string {
	if x != nil {
		return x.Artista
	}
	return ""
}

func (x *AlmacenarAudioRequest) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

func (x *AlmacenarAudioRequest) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *AlmacenarAudioRequest) GetAnio() string {
	if x != nil {
		return x.Anio
	}
	return ""
}

func (x *AlmacenarAudioRequest) GetIdTipo() int32 {
	if x != nil {
		return x.IdTipo
	}
	return 0
}

type AlmacenarAudioResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Guardado          bool                   `protobuf:"varint,1,opt,name=guardado,proto3" json:"guardado,omitempty"`
	IdGenerado        int32                  `protobuf:"varint,2,opt,name=idGenerado,proto3" json:"idGenerado,omitempty"`
	FechaHoraRegistro string                 `protobuf:"bytes,3,opt,name=fechaHoraRegistro,proto3" json:"fechaHoraRegistro,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AlmacenarAudioResponse) Reset() {
	*x = AlmacenarAudioResponse{}
	mi := &file_audio_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlmacenarAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlmacenarAudioResponse) ProtoMessage() {}

func (x *AlmacenarAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlmacenarAudioResponse.ProtoReflect.Descriptor instead.
func (*AlmacenarAudioResponse) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{16}
}

func (x *AlmacenarAudioResponse) GetGuardado() bool {
	if x != nil {
		return x.Guardado
	}
	return false
}

func (x *AlmacenarAudioResponse) GetIdGenerado() int32 {
	if x != nil {
		return x.IdGenerado
	}
	return 0
}

func (x *AlmacenarAudioResponse) GetFechaHoraRegistro() string {
	if x != nil {
		return x.FechaHoraRegistro
	}
	return ""
}

var File_audio_proto protoreflect.FileDescriptor

const file_audio_proto_rawDesc = "" +
	"\n" +
	"\vaudio.proto\x12\tservicios\" \n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\a\n" +
	"\x05Empty\"3\n" +
	"\tTipoAudio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"6\n" +
	"\fAudioResumen\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\";\n" +
	"\rCampoMetadata\x12\x14\n" +
	"\x05clave\x18\x01 \x01(\tR\x05clave\x12\x14\n" +
	"\x05valor\x18\x02 \x01(\tR\x05valor\"@\n" +
	"\x12TiposAudioResponse\x12*\n" +
	"\x05tipos\x18\x01 \x03(\v2\x14.servicios.TipoAudioR\x05tipos\".\n" +
	"\x14AudiosPorTipoRequest\x12\x16\n" +
	"\x06idTipo\x18\x01 \x01(\x05R\x06idTipo\"H\n" +
	"\x15AudiosPorTipoResponse\x12/\n" +
	"\x06audios\x18\x01 \x03(\v2\x17.servicios.AudioResumenR\x06audios\"/\n" +
	"\x13DetalleAudioRequest\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\"2\n" +
	"\x16ReproducirAudioRequest\x12\x18\n" +
	"\aidAudio\x18\x01 \x01(\x05R\aidAudio\"\x8e\x01\n" +
	"\x14DetalleAudioResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06idTipo\x18\x02 \x01(\x05R\x06idTipo\x12\x16\n" +
	"\x06titulo\x18\x03 \x01(\tR\x06titulo\x126\n" +
	"\tmetadatos\x18\x04 \x03(\v2\x18.servicios.CampoMetadataR\tmetadatos\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\rLoginResponse\x12\x18\n" +
	"\aexitoso\x18\x01 \x01(\bR\aexitoso\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"Q\n" +
	"\x17RegistrarUsuarioRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\x18RegistrarUsuarioResponse\x12\x1e\n" +
	"\n" +
	"registrado\x18\x01 \x01(\bR\n" +
	"registrado\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\xa3\x01\n" +
	"\x15AlmacenarAudioRequest\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\x12\x18\n" +
	"\aartista\x18\x02 \x01(\tR\aartista\x12\x16\n" +
	"\x06genero\x18\x03 \x01(\tR\x06genero\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x12\n" +
	"\x04anio\x18\x05 \x01(\tR\x04anio\x12\x16\n" +
	"\x06idTipo\x18\x06 \x01(\x05R\x06idTipo\"\x82\x01\n" +
	"\x16AlmacenarAudioResponse\x12\x1a\n" +
	"\bguardado\x18\x01 \x01(\bR\bguardado\x12\x1e\n" +
	"\n" +
	"idGenerado\x18\x02 \x01(\x05R\n" +
	"idGenerado\x12,\n" +
	"\x11fechaHoraRegistro\x18\x03 \x01(\tR\x11fechaHoraRegistro2\xfa\x03\n" +
	"\x0fMetadataService\x12D\n" +
	"\x11ObtenerTiposAudio\x12\x10.servicios.Empty\x1a\x1d.servicios.TiposAudioResponse\x12Y\n" +
	"\x14ObtenerAudiosPorTipo\x12\x1f.servicios.AudiosPorTipoRequest\x1a .servicios.AudiosPorTipoResponse\x12V\n" +
	"\x13ObtenerDetalleAudio\x12\x1e.servicios.DetalleAudioRequest\x1a\x1f.servicios.DetalleAudioResponse\x12[\n" +
	"\x10RegistrarUsuario\x12\".servicios.RegistrarUsuarioRequest\x1a#.servicios.RegistrarUsuarioResponse\x12:\n" +
	"\x05Login\x12\x17.servicios.LoginRequest\x1a\x18.servicios.LoginResponse\x12U\n" +
	"\x0eAlmacenarAudio\x12 .servicios.AlmacenarAudioRequest\x1a!.servicios.AlmacenarAudioResponse2a\n" +
	"\x10StreamingService\x12M\n" +
	"\x0fReproducirAudio\x12!.servicios.ReproducirAudioRequest\x1a\x15.servicios.AudioChunk0\x01B\x11Z\x0f/serviciosAudiob\x06proto3"

var (
	file_audio_proto_rawDescOnce sync.Once
	file_audio_proto_rawDescData []byte
)

func file_audio_proto_rawDescGZIP() []byte {
	file_audio_proto_rawDescOnce.Do(func() {
		file_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)))
	})
	return file_audio_proto_rawDescData
}

var file_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_audio_proto_goTypes = []any{
	(*AudioChunk)(nil),               // 0: servicios.AudioChunk
	(*Empty)(nil),                    // 1: servicios.Empty
	(*TipoAudio)(nil),                // 2: servicios.TipoAudio
	(*AudioResumen)(nil),             // 3: servicios.AudioResumen
	(*CampoMetadata)(nil),            // 4: servicios.CampoMetadata
	(*TiposAudioResponse)(nil),       // 5: servicios.TiposAudioResponse
	(*AudiosPorTipoRequest)(nil),     // 6: servicios.AudiosPorTipoRequest
	(*AudiosPorTipoResponse)(nil),    // 7: servicios.AudiosPorTipoResponse
	(*DetalleAudioRequest)(nil),      // 8: servicios.DetalleAudioRequest
	(*ReproducirAudioRequest)(nil),   // 9: servicios.ReproducirAudioRequest
	(*DetalleAudioResponse)(nil),     // 10: servicios.DetalleAudioResponse
	(*LoginRequest)(nil),             // 11: servicios.LoginRequest
	(*LoginResponse)(nil),            // 12: servicios.LoginResponse
	(*RegistrarUsuarioRequest)(nil),  // 13: servicios.RegistrarUsuarioRequest
	(*RegistrarUsuarioResponse)(nil), // 14: servicios.RegistrarUsuarioResponse
	(*AlmacenarAudioRequest)(nil),    // 15: servicios.AlmacenarAudioRequest
	(*AlmacenarAudioResponse)(nil),   // 16: servicios.AlmacenarAudioResponse
}
var file_audio_proto_depIdxs = []int32{
	2,  // 0: servicios.TiposAudioResponse.tipos:type_name -> servicios.TipoAudio
	3,  // 1: servicios.AudiosPorTipoResponse.audios:type_name -> servicios.AudioResumen
	4,  // 2: servicios.DetalleAudioResponse.metadatos:type_name -> servicios.CampoMetadata
	1,  // 3: servicios.MetadataService.ObtenerTiposAudio:input_type -> servicios.Empty
	6,  // 4: servicios.MetadataService.ObtenerAudiosPorTipo:input_type -> servicios.AudiosPorTipoRequest
	8,  // 5: servicios.MetadataService.ObtenerDetalleAudio:input_type -> servicios.DetalleAudioRequest
	13, // 6: servicios.MetadataService.RegistrarUsuario:input_type -> servicios.RegistrarUsuarioRequest
	11, // 7: servicios.MetadataService.Login:input_type -> servicios.LoginRequest
	15, // 8: servicios.MetadataService.AlmacenarAudio:input_type -> servicios.AlmacenarAudioRequest
	9,  // 9: servicios.StreamingService.ReproducirAudio:input_type -> servicios.ReproducirAudioRequest
	5,  // 10: servicios.MetadataService.ObtenerTiposAudio:output_type -> servicios.TiposAudioResponse
	7,  // 11: servicios.MetadataService.ObtenerAudiosPorTipo:output_type -> servicios.AudiosPorTipoResponse
	10, // 12: servicios.MetadataService.ObtenerDetalleAudio:output_type -> servicios.DetalleAudioResponse
	14, // 13: servicios.MetadataService.RegistrarUsuario:output_type -> servicios.RegistrarUsuarioResponse
	12, // 14: servicios.MetadataService.Login:output_type -> servicios.LoginResponse
	16, // 15: servicios.MetadataService.AlmacenarAudio:output_type -> servicios.AlmacenarAudioResponse
	0,  // 16: servicios.StreamingService.ReproducirAudio:output_type -> servicios.AudioChunk
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_audio_proto_init() }
func file_audio_proto_init() {
	if File_audio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_proto_rawDesc), len(file_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_audio_proto_goTypes,
		DependencyIndexes: file_audio_proto_depIdxs,
		MessageInfos:      file_audio_proto_msgTypes,
	}.Build()
	File_audio_proto = out.File
	file_audio_proto_goTypes = nil
	file_audio_proto_depIdxs = nil
}
